services:
  fxeth-bootnode-geth:
    restart: always
    hostname: fxeth-bootnode-geth
    env_file:
      - ../config/fixturenet-eth/fixturenet-eth.env
    environment:
      RUN_BOOTNODE: "true"
    image: bpi/fixturenet-eth-geth:local
    volumes:
      - fxeth-bootnode-geth-data:/root/ethdata
    ports:
      - "8545"
      - "8546"
      - "8551"
      - "6060"
      - "9898"
      - "30303"

  fxeth-geth-1:
    restart: always
    hostname: fxeth-geth-1
    cap_add:
      - SYS_PTRACE
    environment:
      BPI_REMOTE_DEBUG: ${BPI_REMOTE_DEBUG:-true}
      BPI_SCRIPT_DEBUG: ${BPI_SCRIPT_DEBUG}
      BPI_ALLOW_UNPROTECTED_TXS: ${BPI_ALLOW_UNPROTECTED_TXS:-false}
    env_file:
      - ../config/fixturenet-eth/fixturenet-eth.env
    image: bpi/fixturenet-eth-geth:local
    volumes:
      - fxeth-geth-1-data:/data
    healthcheck:
      test: ["CMD", "nc", "-v", "localhost", "8545"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 3s
    depends_on:
      - fxeth-bootnode-geth
    ports:
      - "8545"
      - "8546"
      - "8551"
      - "6060"
      - "9898"
      - "30303"
      - "40000"

  fxeth-geth-2:
    restart: always
    hostname: fxeth-geth-2
    healthcheck:
      test: ["CMD", "nc", "-v", "localhost", "8545"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 3s
    environment:
      BPI_KEEP_RUNNING_AFTER_GETH_EXIT: "true"
    env_file:
      - ../config/fixturenet-eth/fixturenet-eth.env
    image: bpi/fixturenet-eth-geth:local
    ports:
      - "8545"
      - "8546"
      - "8551"
      - "6060"
      - "9898"
      - "30303"
    depends_on:
      - fxeth-bootnode-geth
    volumes:
      - fxeth-geth-2-data:/data

  fxeth-bootnode-lighthouse:
    restart: always
    hostname: fxeth-bootnode-lighthouse
    environment:
      RUN_BOOTNODE: "true"
    image: bpi/fixturenet-eth-lighthouse:local
    ports:
      - "4242"
      - "8001"
      - "9001"

  fxeth-lighthouse-1:
    restart: always
    hostname: fxeth-lighthouse-1
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--connect-timeout=1", "--quiet", "-O", "-", "http://localhost:8001/eth/v2/beacon/blocks/head"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    env_file:
      - ../config/fixturenet-eth/fixturenet-eth.env
    environment:
      NODE_NUMBER: "1"
      ETH1_ENDPOINT: http://${STACK_SVC_FXETH_GETH_1}:8545
      EXECUTION_ENDPOINT: http://${STACK_SVC_FXETH_GETH_1}:8551
    image: bpi/fixturenet-eth-lighthouse:local
    volumes:
      - fxeth-lighthouse-1-data:/data
    depends_on:
      fxeth-bootnode-lighthouse:
        condition: service_started
      fxeth-geth-1:
        condition: service_healthy
    ports:
      - "8001"
      - "9001"

  fxeth-lighthouse-2:
    restart: always
    hostname: fxeth-lighthouse-2
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--connect-timeout=1", "--quiet", "-O", "-", "http://localhost:8001/eth/v2/beacon/blocks/head"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    ports:
      - "8001"
      - "9001"
    env_file:
      - ../config/fixturenet-eth/fixturenet-eth.env
    environment:
      NODE_NUMBER: "2"
      ETH1_ENDPOINT: http://${STACK_SVC_FXETH_GETH_2}:8545
      EXECUTION_ENDPOINT: http://${STACK_SVC_FXETH_GETH_2}:8551
      LIGHTHOUSE_GENESIS_STATE_URL: http://${STACK_SVC_FXETH_LIGHTHOUSE_1}:8001/eth/v2/debug/beacon/states/0
    image: bpi/fixturenet-eth-lighthouse:local
    volumes:
      - fxeth-lighthouse-2-data:/data
    depends_on:
      fxeth-bootnode-lighthouse:
        condition: service_started
      fxeth-geth-2:
        condition: service_healthy

volumes:
  fxeth-bootnode-geth-data:
  fxeth-geth-1-data:
  fxeth-geth-2-data:
  fxeth-lighthouse-1-data:
  fxeth-lighthouse-2-data:
